# Generated by Django 3.1.5 on 2021-03-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='for_registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone_nu', models.CharField(max_length=10, unique=True)),
                ('loc', models.CharField(max_length=50)),
            ],
        ),
    ]
