# Generated by Django 3.1.5 on 2021-03-22 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemart_home', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Cartid',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
