# Generated by Django 3.1.5 on 2021-03-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemart_home', '0004_remove_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Big_bazaar_price',
            fields=[
                ('cartid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='D_mart_price',
            fields=[
                ('cartid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='k_mart_price',
            fields=[
                ('cartid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='Cartid',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
