# Generated by Django 3.1.5 on 2021-04-10 12:30

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homemart_home', '0005_auto_20210323_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cartid', models.CharField(max_length=10)),
                ('phone_no', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='customer_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=25)),
                ('l_name', models.CharField(max_length=25)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=25)),
                ('Address1', models.CharField(max_length=75)),
                ('Address2', models.CharField(max_length=75)),
                ('Post_Zip', models.IntegerField(max_length=10)),
                ('Town_City', models.CharField(max_length=25)),
                ('Additional', models.TextField(max_length=100)),
            ],
        ),
    ]
