# Generated by Django 3.1.5 on 2021-04-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homemart_home', '0006_cart_customer_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer_details',
        ),
    ]
