# Generated by Django 3.1.5 on 2021-04-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemart_home', '0007_delete_customer_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shop_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
