# Generated by Django 3.1.5 on 2021-04-10 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homemart_home', '0008_cart_shop_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shop_name',
        ),
    ]
