# Generated by Django 3.2.3 on 2021-05-31 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemart_home', '0009_remove_cart_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shopName',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
