# Generated by Django 3.2.3 on 2021-06-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homemart_home', '0011_shops'),
    ]

    operations = [
        migrations.AddField(
            model_name='shops',
            name='id',
            field=models.AutoField(auto_created=True, default=None, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shops',
            name='cartid',
            field=models.CharField(max_length=10),
        ),
    ]
